### ISSUE TITLE
VCH create wizard fails with runtime error (panic) when container network is specified

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic-ui#259]
**Deployment Detail**
Create a VCH using wizard with container network and firewall setting

**Expected Behavior**
Creation succeeds 

**Actual Behavior**
Deployment failed with `runtime error: invalid memory address or nil pointer dereference`:

![failure](https://user-images.githubusercontent.com/6562128/34118362-1d1adf28-e3e4-11e7-8029-b3c98decdd83.png)

Creation succeeds after removing the container network setting in the wizard.

However the generated CLI command runs successfully, with container network setting:
```
./vic-machine-linux create --name virtual-container-host --compute-resource /RegionA01/host/RegionA01-COMP01 --image-store RegionA01-ISCSI01-COMP01 --base-image-size 8GB --volume-store RegionA01-ISCSI01-COMP01:default --bridge-network Bridge01-RegionA01-vDS-COMP --bridge-network-range 172.16.0.0/12 --public-network VM-RegionA01-vDS-COMP --public-network-ip 192.168.100.22/24 --public-network-gateway 192.168.100.1 --dns-server 192.168.110.10 --container-network VM-RegionA01-vDS-COMP:routable --container-network-firewall VM-RegionA01-vDS-COMP:open --tls-cname vch1.corp.local --organization corp.local --certificate-key-size 2048 --no-tlsverify --whitelist-registry registry.corp.local --whitelist-registry registry.hub.docker.com --registry-ca ca.crt --user Administrator@CORP.LOCAL --thumbprint F7:68:F0:93:F4:EC:B7:FE:C1:02:3F:F3:AB:62:1A:50:E8:9A:0E:85 --target vcsa-01a.corp.local/RegionA01 --ops-user administrator@vsphere.local
```

Request body:
```
{"name":"virtual-container-host","compute":{"cpu":{"limit":{"units":"MHz","value":0}},"memory":{"limit":{"units":"MiB","value":0}},"resource":{"name":"/RegionA01/host/RegionA01-COMP01"}},"storage":{"image_stores":["RegionA01-ISCSI01-COMP01"],"base_image_size":{"units":"GiB","value":8},"volume_stores":[{"datastore":"RegionA01-ISCSI01-COMP01","label":"default"}]},"network":{"bridge":{"ip_range":"172.16.0.0/12","port_group":{"name":"Bridge01-RegionA01-vDS-COMP"}},"public":{"port_group":{"name":"VM-RegionA01-vDS-COMP"},"static":"192.168.100.22/24","gateway":{"address":"192.168.100.1"},"nameservers":["192.168.110.10"]},"container":[{"port_group":{"name":"VM-RegionA01-vDS-COMP"},"alias":"routable","firewall":"open"}]},"auth":{"client":{"no_tls_verify":true},"server":{"generate":{"size":{"value":2048,"units":"bit"},"organization":["virtual-container-host"],"cname":"vch1.corp.local"}}},"container":{},"debug":0,"endpoint":{"operations_credentials":{"user":"administrator@vsphere.local","password":"VMware1!"}},"registry":{}}
```

**Additional Info**
The server log shows that the panic occurs when trying to grab gateway address from container network:
```
address := net.ParseIP(string(cnetwork.Gateway.Address))
```
Might either be a UI-side or API-side parsing issue. 

vic-machine-server.log: 
```
Dec 18 2017 16:40:24.204Z INFO  op=1.16: Request: OPTIONS /container/target/vcsa-01a.corp.local/datacenter/datacenter-21/vch HTTP/1.1
Dec 18 2017 16:40:24.205Z INFO  op=1.16: Response: 200 OK
Dec 18 2017 16:40:24.217Z INFO  op=1.17: Request: POST /container/target/vcsa-01a.corp.local/datacenter/datacenter-21/vch HTTP/1.1
Dec 18 2017 16:40:24.368Z INFO  op=1.17: Validating target
Dec 18 2017 16:40:24.369Z ERROR op=1.17: PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 55 [running]:
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1.1(0xc420406f00, 0x1b63520, 0xc4209c1da0)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:258 +0x13c
panic(0xf4b5a0, 0x1b46270)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.buildCreate(0x1b64ca0, 0xc420829e00, 0xc420732fa0, 0x1, 0x1, 0xc420aff4a0, 0x4, 0xc420733220, 0xc420a2cc00, 0x1b58760, ...)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_create.go:280 +0x1cbb
github.com/vmware/vic/lib/apiservers/service/restapi/handlers.(*VCHDatacenterCreate).Handle(0x1ba9970, 0xc420406f00, 0xc4208a8ad6, 0xd, 0xc4208a8ab7, 0x13, 0xc420aff6f0, 0xc420600500, 0xfa56c0, 0xc420aff690, ...)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/handlers/vch_create.go:117 +0x411
github.com/vmware/vic/lib/apiservers/service/restapi/operations.(*PostTargetTargetDatacenterDatacenterVch).ServeHTTP(0xc4204fefe0, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/operations/post_target_target_datacenter_datacenter_vch.go:64 +0x344
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
net/http.HandlerFunc.ServeHTTP(0xc4201f3150, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/router.go:75 +0x3b2
net/http.HandlerFunc.ServeHTTP(0xc420634c00, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc42050a940, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x82
net/http.HandlerFunc.ServeHTTP(0xc42050a980, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/vendor/github.com/rs/cors/cors.go:200 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc4206351c0, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/lib/apiservers/service/restapi.addPanicRecovery.func1(0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:269 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc420635200, 0x1b63520, 0xc4209c1da0, 0xc420406f00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/lib/apiservers/service/restapi.addLogging.func1(0x1b64060, 0xc4208861c0, 0xc420406e00)
        /go/src/github.com/vmware/vic/lib/apiservers/service/restapi/configure_vic_machine.go:224 +0x440
net/http.HandlerFunc.ServeHTTP(0xc420635220, 0x1b64060, 0xc4208861c0, 0xc420406e00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc4207f3290, 0x1b64060, 0xc4208861c0, 0xc420406e00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4208a8a00, 0x1b64be0, 0xc4209d3f40)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce

Dec 18 2017 16:40:24.369Z INFO  op=1.17: Response: 500 Internal Server Error
```

Pinging people for investigation: @zjs @jak-atx

**Comment by jak-atx** [comment]
We'll need some help here determining if we are not sending in the correctly parsed values that the API is expecting.

**Comment by AngieCris** [comment]
@jak-atx Yea looking into it. The payload it sends does not have the gateway field for container network. This looks more like a API side parsing thing.
I'll compare it with CLI parsing. Once it's confirmed, I'll file a ticket in vic repo

**Comment by AngieCris** [comment]
Root cause identified: https://github.com/vmware/vic/issues/6977
On API side it fails when gateway field is not specified in container network setting

**Comment by jak-atx** [comment]
Currently we disable the gateway field unless ‘static’ is enabled. But it is still possible to enable static, enter a gateway value, then switch to DHCP.

**Comment by jak-atx** [comment]
Closing as addressed in https://github.com/vmware/vic/issues/6977
