### ISSUE TITLE
"Could not find any VIC appliance VM" - VIC v1.3.0.533 on VMware Cloud Foundation 2.3.0

### ISSUE THREAD

**Issue by kciepluc** [vmware/vic-ui#341]
The HTML5 version of VIC-UI reports "Could not find any VIC appliance VM" when deployed on VMware Cloud Foundation (VCF) 2.3.0 Workload Domain.

**VIC-UI version:**
v1.3.0.533 

**Platform details:**
VMware Cloud Foundation (VCF) 2.3.0 deployed using vcf-bundle-2.3.0-7597069 on Dell R640 servers

**Client platform:**
Windows Server 2016 remote desktop

**Browser details:**
Firefox 58.0.1 (64-bit), Internet Explorer 11.44.14393.0

**Steps to reproduce:**

Environment: VMware Cloud Foundation (VCF) 2.3.0 with newly created Workload Domains (WD) which is generally a cluster of ESXi servers with vSAN and NSX-V and a dedicated vCenter Server (Appliance). 

I have VIC 1.3.0 appliance deployed and configured and installed the UI plugin on the vCenter Server Appliance then restarted both HTML5 and Flex-based web client services.

Tried to re-deploy VIC appliance and reinstall plugin several times - nothing helped.

**Actual behavior:**

When I try to access VIC UI it reports "Could not find any VIC appliance VM".
I can successfully deploy and manage VCH using CLI tools (vic-machine-linux).

**Expected behavior:**

The VIC UI should be able to find the VIC appliance automatically, or there should be an option to manually configure which appliance should be used.

**Logs:**
The `vic-ui.log` content:
```
Feb  1 2018 10:27:15.280Z ERROR Failed to verify certificate for target=100.65.0.26 (thumbprint=CB:34:43:90:94:06:19:B0:39:2F:0D:F1:AC:BE:34:8D:29:EE:26:A1)
Feb  1 2018 10:27:15.761Z INFO  ### Installing UI Plugin ####
Feb  1 2018 10:27:15.849Z INFO  Installing plugin
Feb  1 2018 10:27:18.399Z INFO  Installed UI plugin
Feb  1 2018 10:27:18.449Z INFO  ### Installing UI Plugin ####
Feb  1 2018 10:27:18.546Z INFO  Installing plugin
Feb  1 2018 10:27:20.998Z INFO  Installed UI plugin
Feb  1 2018 10:27:21.379Z INFO  Found 1 VM(s) tagged as OVA
Feb  1 2018 10:27:21.383Z INFO  Attempting to configure ManagedByInfo
Feb  1 2018 10:27:21.565Z INFO  Successfully configured ManagedByInfo
```

fragment of `vsphere_client_virgo.log`:
```
[2018-02-02T12:08:00.977Z] [WARN ] data-service-pool-793        70000839 100087 200003 c.v.v.client.iconslabels.IconsLabelsPropertyProviderAdapter       No icon property found
[2018-02-02T12:08:01.098Z] [WARN ] data-service-pool-793        70000842 100087 200003 c.v.v.client.iconslabels.IconsLabelsPropertyProviderAdapter       No icon property found
[2018-02-02T12:08:03.644Z] [INFO ] http-bio-5090-exec-9          com.vmware.vise.util.session.SessionUtil                          Generated hashed session id: 100090
[2018-02-02T12:08:03.644Z] [INFO ] http-bio-5090-exec-9          com.vmware.vise.util.session.SessionUtil                          Mapping: /ui/vic: sessionid to -> 100090 with clientId: 200003
[2018-02-02T12:08:03.645Z] [INFO ] http-bio-5090-exec-9         70000847 100090 200003 com.vmware.vise.util.session.SessionUtil                          Associated sessionId 100090 with clientId 200003. Context path: /ui/vic
[2018-02-02T12:08:03.720Z] [WARN ] data-service-pool-793        70000848 100087 200003 c.v.v.client.iconslabels.IconsLabelsPropertyProviderAdapter       No icon property found
[2018-02-02T12:08:03.728Z] [WARN ] data-service-pool-793        70000845 100087 200003 c.v.v.client.iconslabels.IconsLabelsPropertyProviderAdapter       No icon property found
[2018-02-02T12:08:04.125Z] [WARN ] http-bio-5090-exec-5          com.vmware.vic.PropFetcher                                        No VIC appliance was found
[2018-02-02T12:08:04.156Z] [WARN ] data-service-pool-793        70000850 100087 200003 c.v.v.client.iconslabels.IconsLabelsPropertyProviderAdapter       No icon property found
[2018-02-02T12:08:04.163Z] [ERROR] http-bio-5090-exec-9         70000850 100087 200003 com.vmware.vise.mvc.servlets.GlobalExceptionResolver              Exception handled:  com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: The object 'vim.view.ContainerView:session[52b8e86b-8dbc-c672-4a6a-78e82df1155b]5264dff5-74eb-2cba-9eec-375a2dbddf55' has already been deleted or has not been completely created Please see the server log to find more detail regarding exact cause of the failure.
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:124)
        at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
        at com.sun.proxy.$Proxy706.retrievePropertiesEx(Unknown Source)
        at com.vmware.vic.PropFetcher.getVicVms(PropFetcher.java:264)
        at com.vmware.vic.ObjectStore.getRootObject(ObjectStore.java:96)
        at com.vmware.vic.ObjectStore.getObj(ObjectStore.java:125)
        at com.vmware.vic.VicUIDataAdapter.processObjectIdentityConstraint(VicUIDataAdapter.java:161)
        at com.vmware.vic.VicUIDataAdapter.processConstraint(VicUIDataAdapter.java:127)
        at com.vmware.vic.VicUIDataAdapter.processQuerySpec(VicUIDataAdapter.java:106)
        at com.vmware.vic.VicUIDataAdapter.getData(VicUIDataAdapter.java:86)
        at com.vmware.vise.data.query.impl.DataAdapterUtil.getDataFromAdapter(DataAdapterUtil.java:219)
        at com.vmware.vise.data.query.impl.DataAdapterUtil.getResultFromAdapter(DataAdapterUtil.java:176)
        at com.vmware.vise.data.query.impl.DataAdapterUtil.access$000(DataAdapterUtil.java:43)
        at com.vmware.vise.data.query.impl.DataAdapterUtil$1.call(DataAdapterUtil.java:82)
        at com.vmware.vise.data.query.impl.DataAdapterUtil$1.call(DataAdapterUtil.java:79)
        at com.vmware.vise.util.concurrent.ExecutorUtil$2.call(ExecutorUtil.java:693)
        at com.vmware.vise.util.concurrent.ExecutorUtil$ThreadContextPropagatingTask.call(ExecutorUtil.java:1062)
        at com.vmware.vise.data.query.impl.DataServiceThreadPoolDecorator$1.call(DataServiceThreadPoolDecorator.java:167)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[2018-02-02T12:08:04.167Z] [ERROR] http-bio-5090-exec-9          o.a.c.core.ContainerBase.[Catalina].[localhost].[/ui].[spring]    Servlet.service() for servlet [spring] in context with path [/ui] threw exception [Request processing failed; nested exception is com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: The object 'vim.view.ContainerView:session[52b8e86b-8dbc-c672-4a6a-78e82df1155b]5264dff5-74eb-2cba-9eec-375a2dbddf55' has already been deleted or has not been completely created Please see the server log to find more detail regarding exact cause of the failure.] with root cause com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: The object 'vim.view.ContainerView:session[52b8e86b-8dbc-c672-4a6a-78e82df1155b]5264dff5-74eb-2cba-9eec-375a2dbddf55' has already been deleted or has not been completely created Please see the server log to find more detail regarding exact cause of the failure.
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:124)
        at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
        at com.sun.proxy.$Proxy706.retrievePropertiesEx(Unknown Source)
        at com.vmware.vic.PropFetcher.getVicVms(PropFetcher.java:264)
        at com.vmware.vic.ObjectStore.getRootObject(ObjectStore.java:96)
        at com.vmware.vic.ObjectStore.getObj(ObjectStore.java:125)
        at com.vmware.vic.VicUIDataAdapter.processObjectIdentityConstraint(VicUIDataAdapter.java:161)
        at com.vmware.vic.VicUIDataAdapter.processConstraint(VicUIDataAdapter.java:127)
        at com.vmware.vic.VicUIDataAdapter.processQuerySpec(VicUIDataAdapter.java:106)
        at com.vmware.vic.VicUIDataAdapter.getData(VicUIDataAdapter.java:86)
        at com.vmware.vise.data.query.impl.DataAdapterUtil.getDataFromAdapter(DataAdapterUtil.java:219)
        at com.vmware.vise.data.query.impl.DataAdapterUtil.getResultFromAdapter(DataAdapterUtil.java:176)
        at com.vmware.vise.data.query.impl.DataAdapterUtil.access$000(DataAdapterUtil.java:43)
        at com.vmware.vise.data.query.impl.DataAdapterUtil$1.call(DataAdapterUtil.java:82)
        at com.vmware.vise.data.query.impl.DataAdapterUtil$1.call(DataAdapterUtil.java:79)
        at com.vmware.vise.util.concurrent.ExecutorUtil$2.call(ExecutorUtil.java:693)
        at com.vmware.vise.util.concurrent.ExecutorUtil$ThreadContextPropagatingTask.call(ExecutorUtil.java:1062)
        at com.vmware.vise.data.query.impl.DataServiceThreadPoolDecorator$1.call(DataServiceThreadPoolDecorator.java:167)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[2018-02-02T12:08:04.171Z] [ERROR] http-bio-5090-exec-9          o.a.c.core.ContainerBase.[Catalina].[localhost].[/ui].[jsp]       Servlet.service() for servlet jsp threw exception java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at org.apache.catalina.connector.Response.getWriter(Response.java:663)
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:213)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:152)
        at org.apache.jasper.runtime.JspWriterImpl.initOut(JspWriterImpl.java:125)
        at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:118)
        at org.apache.jasper.runtime.PageContextImpl.release(PageContextImpl.java:186)
        at org.apache.jasper.runtime.JspFactoryImpl.internalReleasePageContext(JspFactoryImpl.java:125)
        at org.apache.jasper.runtime.JspFactoryImpl.releasePageContext(JspFactoryImpl.java:79)
        at org.apache.jsp.error_jsp._jspService(error_jsp.java:246)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:473)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:341)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:434)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:204)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
        at org.eclipse.virgo.web.tomcat.support.ApplicationNameTrackingValve.invoke(ApplicationNameTrackingValve.java:33)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

[2018-02-02T12:08:04.174Z] [ERROR] http-bio-5090-exec-9          org.apache.catalina.core.ContainerBase.[Catalina].[localhost]     Exception Processing ErrorPage[errorCode=0, location=/error.jsp] org.apache.jasper.JasperException: java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:597)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:472)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:473)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:341)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:434)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:204)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
        at org.eclipse.virgo.web.tomcat.support.ApplicationNameTrackingValve.invoke(ApplicationNameTrackingValve.java:33)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at org.apache.catalina.connector.Response.getWriter(Response.java:663)
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:213)
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:152)
        at org.apache.jasper.runtime.JspWriterImpl.initOut(JspWriterImpl.java:125)
        at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:118)
        at org.apache.jasper.runtime.PageContextImpl.release(PageContextImpl.java:186)
        at org.apache.jasper.runtime.JspFactoryImpl.internalReleasePageContext(JspFactoryImpl.java:125)
        at org.apache.jasper.runtime.JspFactoryImpl.releasePageContext(JspFactoryImpl.java:79)
        at org.apache.jsp.error_jsp._jspService(error_jsp.java:246)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
        ... 25 common frames omitted
```

full log attached (compressed)
[vsphere_client_virgo.zip](https://github.com/vmware/vic-ui/files/1689407/vsphere_client_virgo.zip)

*Note:* @zjs edited this comment on 2018-02-12 to fix some minor formatting issues.

**Comment by AngieCris** [comment]
@jooskim @jak-atx Have you guys seen this before?
This reminded me of https://github.com/vmware/vic-ui/issues/222 where this error was seen when H5 client session expires, but in this ticket the customer re-installed the plugin and re-deployed the VIC appliance, the error still appears

**Comment by jooskim** [comment]
@AngieCris This does not seem related to H5C session expiry, but rather like that the OVA appliance was not registered with VC correctly. @kciepluc can you show me in your VC's Hosts and Clusters view showing the VIC appliance VM?

The icon next to the appliance VM name should be slightly different from other VMs that are not managed by any vSphere extension. See the following screenshot.

![image](https://user-images.githubusercontent.com/3834071/35753330-f66b189c-0824-11e8-90f4-9767e118c256.png)

**Comment by krisiasty** [comment]
Sorry for delayed answer, here is the screenshot from H5C:

![image](https://user-images.githubusercontent.com/6045259/35996982-6b280fb2-0d18-11e8-8c5e-fbd9ed313ea5.png)

**Comment by jooskim** [comment]
@krisiasty I see in the screenshot two instances of vCenter Server in the left hand side tree. Could you confirm your VC is running in the enhanced linked mode?

**Comment by kciepluc** [comment]
@jooskim That is most certainly correct, although official VCF documentation doesn't mention ELM specifically.
VMware Cloud Foundation uses external Platform Services Controller(s) and all vCenter Servers (each Workload Domain has separate VC) are connected to these PSC forming single SSO Domain.

**Comment by dgshue** [comment]
@jooskim I'm experiencing this as well, vCenter Standard - 6.5.0.14000 Build Number 7515524

**Comment by jooskim** [comment]
@dgshue can you confirm you're running your VC in the Enhanced Linked Mode?

**Comment by krisiasty** [comment]
Is there any known workaround how to fix that manually while you work on proper fix ?

**Comment by dgshue** [comment]
@jooskim  Confirmed, with separate PSCs as well. PSC - 6.5.0.5600 Build Number 5705665

_**I have only added the plugin to NC-VCA01**_ (twice now, one install.sh and second time with upgrade.sh)
Flex does not show the plugin although it does show installed.

![image](https://user-images.githubusercontent.com/12952156/36266179-df5b1016-123e-11e8-81a1-ed0a84fbebc2.png)

![image](https://user-images.githubusercontent.com/12952156/36266628-e939853a-123f-11e8-9036-6c2a57c22265.png)

![image](https://user-images.githubusercontent.com/12952156/36266634-f033f21c-123f-11e8-9bd7-6f553159029e.png)

**Comment by jooskim** [comment]
Unfortunately the bug is fundamentally inside the service part so unless the code change is made there really is not much workaround. I have this issue as one of my top priorities for this sprint so I will do my best to resolve it asap.
