### ISSUE TITLE
VIC plugin failed to register on vCenter 6.7 U1

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic-ui#564]
**User Statement:**
VIC plugin failed to register on vCenter 6.7 U1
VIC Version: Version: 1.4.1.1262 
vCenter : BUILDNUMBER: 9121219 

**Details:**
The output shows VIC plugin is successfully installed. But VIC plugin is missing from both html5 and flex vSphere Web Client.

**Acceptance Criteria:**
After restart vsphere-ui and vsphere-client, VIC plugin should show in vSphere web client

#For bug reports, please include the information below:
[vsphere_client_virgo_0.log.zip](https://github.com/vmware/vic-ui/files/2217755/vsphere_client_virgo_0.log.zip)
[install output.txt](https://github.com/vmware/vic-ui/files/2217760/install.output.txt)

**VIC-UI version:**
VIC Version: 1.4.1.1262
If applicable: 

[In the VIC plugin] > Summary tab > Version

**Platform details:**

Which platform are you using? (Windows, Mac OS, Linux, etc)
Mac OS

**Browser details:**
Which browser are you using? (IE, Chrome, Firefox, etc)
Firefox

**Logs:**
If applicable attach vsphere_client_virgo.log

See:
[2018-07-20T09:21:48.689Z] [ERROR] fs-watcher                    org.eclipse.virgo.medic.eventlog.default                         DE0002E Installation of par 'com.vmware.vic' version '1.4.1.1262' failed. org.eclipse.virgo.kernel.osgi.framework.UnableToSatisfyBundleDependenciesException: Unable to satisfy dependencies of bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' at version '1.0.0': Cannot resolve: com.vmware.vic-1.4.1.1262-com.vmware.vic.service 
    Resolver report:
        An Import-Package could not be resolved. Resolver error data <Import-Package: org.springframework.http; version="[3.1.4,4.3.9.RELEASE_VMWARE]">. Caused by missing constraint in bundle <com.vmware.vic-1.4.1.1262-com.vmware.vic.service_1.0.0>
             constraint: <Import-Package: org.springframework.http; version="[3.1.4,4.3.9.RELEASE_VMWARE]">
        An Import-Package could not be resolved. Resolver error data <Import-Package: com.vmware.vic.services; version="0.0.0">. Caused by missing constraint in bundle <com.vmware.vic-1.4.1.1262-synthetic.context_1.4.1.1262>
             constraint: <Import-Package: com.vmware.vic.services; version="0.0.0"> constrained to bundle <com.vmware.vic-1.4.1.1262-com.vmware.vic.service> constrained bundle version range "[1.0.0,1.0.0]"
            with attributes {module_scope=com.vmware.vic-1.4.1.1262}

        An Import-Package could not be resolved. Resolver error data <Import-Package: com.vmware.vic.services; version="1.0.0">. Caused by missing constraint in bundle <com.vmware.vic-1.4.1.1262-com.vmware.vic.ui_1.0.0>
             constraint: <Import-Package: com.vmware.vic.services; version="1.0.0">
            with attributes {module_scope=com.vmware.vic-1.4.1.1262}

        at org.eclipse.virgo.kernel.install.pipeline.stage.resolve.internal.QuasiResolveStage.process(QuasiResolveStage.java:46)
        at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
        at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
        at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
        at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
        at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
        at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
        at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.doInstall(PipelinedApplicationDeployer.java:185)
        at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.install(PipelinedApplicationDeployer.java:140)
        at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.deploy(PipelinedApplicationDeployer.java:253)
        at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deploy(HotDeployerFileSystemListener.java:225)
        at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.onChange(HotDeployerFileSystemListener.java:79)
        at org.eclipse.virgo.util.io.FileSystemChecker.notifyListeners(FileSystemChecker.java:380)
        at org.eclipse.virgo.util.io.FileSystemChecker.check(FileSystemChecker.java:289)
        at org.eclipse.virgo.nano.deployer.hot.WatchTask.run(WatchTask.java:49)
        at java.lang.Thread.run(Thread.java:748)

[2018-07-20T09:21:48.690Z] [INFO ] fs-watcher                    o.e.v.k.m.i.deployer.ModelInstallArtifactLifecycleListener        Processing install failed event for bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' version '1.0.0'
[2018-07-20T09:21:48.691Z] [ERROR] fs-watcher                    org.eclipse.virgo.medic.eventlog.default                         DE0003E Install failed for bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' version '1.0.0'.
[2018-07-20T09:21:48.691Z] [INFO ] fs-watcher                    o.e.v.k.m.i.deployer.ModelInstallArtifactLifecycleListener        Processing install failed event for bundle 'com.vmware.vic-1.4.1.1262-com.google.gson' version '2.3.1'
[2018-07-20T09:21:48.691Z] [ERROR] fs-watcher                    org.eclipse.virgo.medic.eventlog.default                         DE0003E Install failed for bundle 'com.vmware.vic-1.4.1.1262-com.google.gson' version '2.3.1'.
[2018-07-20T09:21:48.691Z] [INFO ] fs-watcher                    o.e.v.k.m.i.deployer.ModelInstallArtifactLifecycleListener        Processing install failed event for bundle 'com.vmware.vic-1.4.1.1262-com.vmware.wsvim25' version '6.0.2'
[2018-07-20T09:21:48.692Z] [ERROR] fs-watcher                    org.eclipse.virgo.medic.eventlog.default                         DE0003E Install failed for bundle 'com.vmware.vic-1.4.1.1262-com.vmware.wsvim25' version '6.0.2'.

**Additional details as necessary:**

**Comment by lgayatri** [comment]
We can plan to fix this in the next vic release.

**Comment by renmaosheng** [comment]
@javierfz1980 could you please take a look at this issue?

**Comment by javierfz1980** [comment]
Hi guys, I'm not being able to find the OVA containing `VIC Version: Version: 1.4.1.1262` to test it in a fresh VC installation.
Could you please provide the exact OVA version/link deployed so I can try to reproduce it ?

Thanks.

**Comment by javierfz1980** [comment]
Hi guys, forget about my las comment... I've been able to reproduce the issue with the following environment specs: 

**VC: vsphere67u1** -> https://buildweb.eng.vmware.com/ob/9121219/
**ESX: vsphere67u1** -> https://buildweb.eng.vmware.com/ob/9267045/
**VIC Ova:  release 1.4.1 vic-v1.4.1-5547-ad7eb5f8.ova** -> https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.4.1-5547-ad7eb5f8.ova?_ga=2.80742928.-68607680.1531311033

**environment could be available for 7 days here:**
https://10.160.188.34/
administrator@vsphere.local
Admin!23

**Analysis:**
I've been doing a triage and looking the logs. IMHO the problem seems to be related with a wrong springframework import version in VIC MANIFEST.

Looking ate the logs It seems like it starts deploying the VIC bundle but it fails because it is not able to satisfy a dependency: `An Import-Package could not be resolved. Resolver error data <Import-Package: org.springframework.http; version="[3.1.4,4.3.9.RELEASE_VMWARE]"` 

It looks like this version of vCenter 67u1 is not providing the springframework version expected by VIC MANIFEST. VIC MANIFEST imports `version="[3.1.4,4.3.9.RELEASE_VMWARE]` and vc67u1 is providing `4.3.17` 

**Here are the logs:**
root@sc-rdops-vm06-dhcp-188-34 [ /var/log/vmware/vsphere-ui ]# clear
root@sc-rdops-vm06-dhcp-188-34 [ /var/log/vmware/vsphere-ui ]# grep -r -w 'com.vmware.vic'
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:31.744Z] [INFO ] plugin-deploy10               <XF1000I> Deploying plugin package 'com.vmware.vic' version '1.4.1.1262'.
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:32.870Z] [INFO ] fs-watcher                    <HD0001I> Hot deployer processing 'CREATED' event for file 'com.vmware.vic-1.4.1.1262.par'.
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:33.746Z] [INFO ] fs-watcher                    <DE0000I> Installing par 'com.vmware.vic' version '1.4.1.1262'.
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:33.753Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' version '1.0.0'.
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:33.754Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.google.gson' version '2.3.1'.
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:33.755Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.vmware.wsvim25' version '6.0.2'.
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:33.756Z] [INFO ] fs-watcher                    <DE0000I> Installing bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.ui' version '1.0.0'.
logs/vsphere-ui-runtime.log.stdout:[2018-07-24T17:15:33.841Z] [ERROR] fs-watcher                    <DE0002E> Installation of par 'com.vmware.vic' version '1.4.1.1262' failed. org.eclipse.virgo.kernel.osgi.framework.UnableToSatisfyBundleDependenciesException: Unable to satisfy dependencies of bundle 'com.vmware.vic-1.4.1.1262-com.vmware.vic.service' at version '1.0.0': Cannot resolve: com.vmware.vic-1.4.1.1262-com.vmware.vic.service
logs/vsphere-ui-runtime.log.stdout:        An Import-Package could not be resolved. Resolver error data <Import-Package: org.springframework.http; version="[3.1.4,4.3.9.RELEASE_VMWARE]">. Caused by missing constraint in bundle <com.vmware.vic-1.4.1.1262-com.vmware.vic.service_1.0.0>

Please note that our current MANIFEST is looking for version: `[3.1.4,4.3.9.RELEASE_VMWARE]` 
https://github.com/vmware/vic-ui/blob/master/h5c/vic/src/main/webapp/META-INF/MANIFEST.MF

I've downloaded the SDK of the current vCenter 67u1 from buildweb and it contains a different version of springframework `4.3.17`: (tab deliverables -> vsphereclient/vsphere-client-sdk-6.7.0-9112392.zip): https://buildweb.eng.vmware.com/ob/9121219/ 

I've also compared 3 different VC sdk versions and VIC ui MANIFEST import is compatible with two of them but not with vc67u1, please look the following screenshots:

vsphere65ep5
<img width="867" alt="vc65ep5-spring-version" src="https://user-images.githubusercontent.com/36636787/43160345-41b2fe24-8f5b-11e8-9542-94c85f8140b2.png">

vsphere67
<img width="703" alt="vc67-spring-version" src="https://user-images.githubusercontent.com/36636787/43160357-48777154-8f5b-11e8-8a83-1ef8b87672be.png">

vsphere67u1
<img width="723" alt="vc67u1-spring-version" src="https://user-images.githubusercontent.com/36636787/43160365-4d6d4c2e-8f5b-11e8-9e57-68e677b09738.png">

**Possible Fix**
I belive the better aproach to try to fix this issue will be to update our manifest to also inclide the new springframework version `4.3.17` provided by vsphere67u1

Regards
